// TIMER ACTIONS
export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const TICK_TIMER = 'TICK_TIMER';
export const ZERO_TIMER = 'ZERO_TIMER';
// BUTTON GAMEPLAY ACTIONS
export const CLICK_ANSWER = 'CLICK_ANSWER';

export const CLEAR_FUEL_SAVINGS = 'CLEAR_FUEL_SAVINGS';
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
