SELECT ID, FIRSTNAME, LASTNAME, CLIP_NAME FROM voices WHERE id=642
union all (
  SELECT ID, FIRSTNAME, LASTNAME, CLIP_NAME FROM  voices 
  WHERE id!=642 AND CATEGORY='Movies/TV' AND GENDER='Male' AND ACCENT='US' AND RACE='White' AND DOB='1946-1964'
  ORDER BY RAND() LIMIT 0,4)